reference FHIR R4 and change links to https
gematik/ISiK-Dokumentenaustausch pull request #158
Opened 2023-11-15 09:53 UTC by MaxMTheilig

2023-11-15 12:41 UTC, f-peverali requested changes
@MaxMTheilig lass uns auf die Rückmeldung von @simoneOnFhir, bzw @ylboerner warten, bevor wir hier mergen.

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +* type.coding[KDL] from https://dvmd.de/fhir/kdl (required)
@MaxMTheilig hier bin ich unsicher, wie gesagt.
@simoneOnFhir passt die Referenzierung der KDL Liste so?

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +  * system = "https://dvmd.de/fhir/kdl"
s.o.

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +    * ^comment = "Fix: &quot;https://dvmd.de/fhir/kdl&quot;"
s.o.

2023-11-15 12:41 UTC, f-peverali commented on Materialien/UseCases_ITI-66-67.md
> +* Selektion nach Dokumenttyp "Endoskopiebefund" und Dokumentationsstatus (`docStatus`) `/DocumentReference?type=DG02010|https://dvmd.de/fhir/kdl&doc-status=preliminary`
unsichee , ob das so passt. s.u.

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/aliases.fsh
> +Alias: $kdl = https://dvmd.de/fhir/kdl
s.o.

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/capabilitystatement.fsh
> +  * extension.url = "https://hl7.org/fhir/R4/StructureDefinition/capabilitystatement-expectation"
das sind Canonicals, denke ich - siehe z.B.: http://hl7.org/fhir/StructureDefinition/capabilitystatement-expectation

Ich denke das R4 ist hier fehl am Platz... wie mi "https" umgegangen wird, kp.
@ylboerner, @simoneOnFhir wisst ihr mehr dazu?

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/referencedExamples.fsh
> +  * extension[+].url = "https://hl7.org/fhir/R4/StructureDefinition/humanname-own-name"
hier analog zu oben ("URL for this extension: http://hl7.org/fhir/R4/extension-humanname-own-name.html")

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/referencedExamples.fsh
> +  * extension[+].url = "https://hl7.org/fhir/R4/StructureDefinition/humanname-own-name"
... gilt für alle URL-Änderungen in diesem Dokument

2023-11-15 12:41 UTC, f-peverali commented on Resources/input/fsh/terminologies.fsh
> +*  https://terminology.hl7.org/CodeSystem/v3-Confidentiality#N	"normal"
auch hier "Official URL: http://terminology.hl7.org/CodeSystem/v3-Confidentiality"

2023-11-16 12:57 UTC, MaxMTheilig commented on Resources/input/fsh/terminologies.fsh
> +*  https://terminology.hl7.org/CodeSystem/v3-Confidentiality#N	"normal"
HTTPS unproblematisch.
Aber zu klären wäre noch wie/ob man hier jeweils das aktuellste aus v4.x.x. referzieren kann. Die offizielle URL forwardes immer auf v5.y.y.

2023-11-16 17:23 UTC, simoneOnFhir commented
Ui, Achtung! 

Die Links im Prosa auf die FHIR-Spec hart mit R4 zu verdrahten geht in Ordnung, aber BITTEBITTE nicht die Canonical URLs in den FSH-Dateien ändern!! Damit gehen alle Referenzen zwischen den Artefakten kaputt. Canonicals sind keine Links, sie sind eindeutige Namen von Artefakten, die nicht mehr matchen, sobald man einen einzigen Buchstaben ändert. Auch die Änderung auf https wäre hier fatal. BITTE NICHT MERGEN!!

Was genau ist dann das Problem, was hier behoben werden soll?

2023-11-16 17:31 UTC, simoneOnFhir commented
Geht grundsätzlich davon aus, dass jede Änderung einer URL in den FSH-Dateien fatale Konsequenzen hätte, da es sich um Canonicals handelt.

Aber selbst in Markdown-Dateien muss man genau hinschauen:

Sowas hier ist ok: 
[`Provenance`-Ressource](http://hl7.org/fhir/provenance.html)
--> [`Provenance`-Ressource](https://hl7.org/fhir/R4/provenance.html).

Diese Änderung wäre jedoch falsch, da nicht Link sondern Canonical:
 `/DocumentReference?type=DG02010|http://dvmd.de/fhir/CodeSystem/kdl&doc-status=preliminary`
--> `/DocumentReference?type=DG02010|https://dvmd.de/fhir/kdl&doc-status=preliminary`


Bestes Vorgehen wäre hier nichts zu ändern, was nicht im Markdown als Link `[text](url)` formatiert ist.

2023-11-17 14:54 UTC, MaxMTheilig commented on Resources/input/fsh/OperationUpdateMetadata.fsh
> +    * valueSet = "https://hl7.org/fhir/R4/ValueSet/composition-status"
@simoneOnFhir Was wäre deine Empfehlung für diese Stelle hier. auf R5 lassen oder zu R4 verdrahten?

2023-11-20 08:59 UTC, f-peverali commented
> Sowas hier ist ok: `[`Provenance`-Ressource](http://hl7.org/fhir/provenance.html)` `--> [`Provenance`-Ressource](https://hl7.org/fhir/R4/provenance.html).`

Im wesentlich ging es darum, dass unsere Refs zur Core-Spec nach R4 auflösen; also wie oben.

2023-11-20 09:14 UTC, f-peverali requested changes
In den fsh Files müssen alle Änderungen mit "https" und "R4" zurückgenommen werden ( mit der einen Ausnahme im Feld "comment").  -> DONE

2023-11-20 09:14 UTC, f-peverali commented on ImplementationGuide/markdown/AkteureUndInteraktionen-Dokumentenabfrage.md
> +  `[base]/DocumentReference?type=https://dvmd.de/fhir/kdl|DG02010&doc-status=preliminary`
```suggestion
  `[base]/DocumentReference?type=http://dvmd.de/fhir/kdl|DG02010&doc-status=preliminary`
```

2023-11-20 09:14 UTC, f-peverali commented on ImplementationGuide/markdown/AkteureUndInteraktionen-Dokumentenabfrage.md
> +  `[base]/DocumentReference?type=https://dvmd.de/fhir/kdl|DG02010&doc-status=preliminary`
siehe dazu Kommentar von Simone

2023-11-20 09:14 UTC, f-peverali commented on Materialien/UseCases_ITI-66-67.md
> +* Selektion nach Dokumenttyp "Endoskopiebefund" und Dokumentationsstatus (`docStatus`) `/DocumentReference?type=DG02010|https://dvmd.de/fhir/kdl&doc-status=preliminary`
```suggestion
* Selektion nach Dokumenttyp "Endoskopiebefund" und Dokumentationsstatus (`docStatus`) `/DocumentReference?type=DG02010|http://dvmd.de/fhir/CodeSystem/kdl&doc-status=preliminary`
```

2023-11-20 09:14 UTC, f-peverali commented on Materialien/UseCases_ITI-66-67.md
> +* Selektion nach Dokumenttyp "Endoskopiebefund" und Dokumentationsstatus (`docStatus`) `/DocumentReference?type=DG02010|https://dvmd.de/fhir/kdl&doc-status=preliminary`
@simoneOnFhir könntest Du dir hier die URL nochmal anschauen (jenseits des https) . Denke die Änderung ist falsch. aber weiß auch nicht, ober die alte Canonical gültig ist..
Wie könnten wir hier die Korrektheit der KDL-Canonical prüfen?

2023-11-20 09:14 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +* type.coding[XDS] from https://ihe-d.de/ValueSets/IHEXDStypeCode (required)
```suggestion
* type.coding[XDS] from http://ihe-d.de/ValueSets/IHEXDStypeCode (required)
```

2023-11-20 09:14 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +* type.coding[KDL] from https://dvmd.de/fhir/kdl (required)
s.o.

2023-11-20 09:14 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +* type.coding[KDL] from https://dvmd.de/fhir/kdl (required)
```suggestion
* type.coding[KDL] from http://dvmd.de/fhir/ValueSet/kdl (required)
```

2023-11-20 09:14 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +* category.coding[XDS] from https://ihe-d.de/ValueSets/IHEXDSclassCode (required)
s.o.

2023-11-20 09:14 UTC, f-peverali commented on Resources/input/fsh/ISiKDokumentenMetadaten.fsh
> +  * format from https://ihe-d.de/ValueSets/IHEXDSformatCodeDE (required)
s.o.

2023-11-20 10:13 UTC, f-peverali approved these changes

2023-11-20 10:16 UTC, merged